import rehypeKatex from 'rehype-katex'
import rehypeSanitize, { defaultSchema } from 'rehype-sanitize'
import remarkGfm from 'remark-gfm'
import remarkMath from 'remark-math'
import type { PluggableList } from 'unified'
import { remarkBlockMeta } from './remarkBlockMeta'

type Attributes = NonNullable<typeof defaultSchema.attributes>

function withAttributes(extra: Attributes): Attributes {
  const base = defaultSchema.attributes ?? {}
  const merged: Attributes = { ...base }
  for (const [tag, values] of Object.entries(extra)) {
    merged[tag] = [...(base[tag] ?? []), ...values]
  }
  return merged
}

/**
 * Raw HTML never reaches the tree (rehype-raw is deliberately not installed),
 * so sanitization here is mainly about URL protocols and about keeping the
 * className allowlist narrow — untrusted content must not be able to borrow the
 * host application's CSS classes.
 */
const sanitizeSchema = {
  ...defaultSchema,
  protocols: {
    ...defaultSchema.protocols,
    href: ['http', 'https', 'mailto'],
    src: ['http', 'https'],
  },
  attributes: withAttributes({
    // remark-math marks math nodes with these classes; rehype-katex needs them.
    span: [['className', 'math', 'math-inline', 'math-display']],
    div: [['className', 'math', 'math-inline', 'math-display']],
    // GFM footnotes.
    section: [['className', 'footnotes']],
    a: [['className', 'data-footnote-backref', 'footnote-ref']],
    // Fence meta carried through by remarkBlockMeta.
    code: ['dataMeta'],
  }),
}

export const remarkPlugins: PluggableList = [remarkGfm, remarkMath, remarkBlockMeta]

/**
 * Sanitize runs before KaTeX: everything KaTeX emits afterwards is generated by
 * KaTeX itself from already-sanitized source (with `trust` left off), so it is
 * safe, while the math source it reads has been through the allowlist.
 */
export const rehypePlugins: PluggableList = [
  [rehypeSanitize, sanitizeSchema],
  [
    rehypeKatex,
    {
      errorColor: 'var(--ucr-error-color, #c5303a)',
      // Untrusted input must not be able to hang the renderer with an
      // expression that expands without bound.
      maxExpand: 1000,
      maxSize: 100,
      strict: 'ignore',
    },
  ],
]
